version: "3.9"

services:
   api:
      build:
         context: .
         dockerfile: ./docker/local/django/Dockerfile
      command: /start
      volumes:
         - .:/app
      # ports:
      #    - 8000:8000
      env_file:
         - .env
      depends_on:
         - postgres-db
      networks:
         - blog-api

   postgres-db:
      image: postgres:12.0-alpine
      ports:
         - 5432:5432
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      networks:
         - blog-api

   nginx:
      restart: always
      depends_on:
         - api
      build:
         context: ./docker/local/nginx
         dockerfile: Dockerfile
      ports:
         - 8080:80
      networks:
         - blog-api

networks:
   blog-api:
      driver: bridge

volumes:
   postgres_data:
